"""Shared defaults used by the CLI and the application services."""

DEFAULT_CLIP_DURATION = 1.0
DEFAULT_CUT_PADDING_SECONDS = 4.0
DEFAULT_ANALYSIS_MAX_DIMENSION = 1280
DEFAULT_EXPOSED_THRESHOLD = 0.15
DEFAULT_COVERED_THRESHOLD = 0.65
DEFAULT_NSFW_THRESHOLD = 0.50
DEFAULT_HUGGINGFACE_MODEL = "Falconsai/nsfw_image_detection"
DEFAULT_DETECTOR_BACKEND = "nudenet"
